name: coverage
on:
  push:
    branches: [main]
  pull_request:
    type: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
