name: bnotes.bnnguyen.ca
on:
  push:
    paths:
      - '!README.md' # ignore README.md file changes
      - '!docs/**' # ignore docs folder and subfolders changes 
      - '**.html' # only html files changes
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY = $(date + %%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
