name: hello world
on:

  push:
    paths:
      - '!README.md' # ignore README.md file changes
      - '!docs/**' # ignore docs folder and subfolders changes 
      - '**.js' # only js files changes
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
    type: [opened, reopened, synchronize]

  workflow_dispatch: # manually trigger workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name == 'pull_request'}}
        uses: mheap/github-action-required-labels@v1 # https://github.com/marketplace?category=mobile&type=actions&query=required+label
        with:
          mode: exactly
          count: 0
          labels: "do not build"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
      - run: docker image ls     
